### ISSUE TITLE
Using the `derive` feature with latest version doesn't build

### ISSUE THREAD

**Issue by kareemmahlees** [oscartbeaumont/tauri-specta#121]
I am trying to pump my versions after the latest `specta` and `tauri-specta` releases and I am trying to enable the `derive` feature for `tauri-specta`, getting this:
```
error: failed to select a version for the requirement `tauri-specta-macros = "=2.0.0-rc.6"`
candidate versions found which didn't match: 2.0.0-rc.5, 2.0.0-rc.4, 2.0.0-rc.3, ...
location searched: crates.io index
required by package `tauri-specta v2.0.0-rc.15`
    ... which satisfies dependency `tauri-specta = "^2.0.0-rc.15"` (locked to 2.0.0-rc.15) of package `tx_lib v0.3.4 (D:\Programming\projects\tablex\crates\lib)`
    ... which satisfies path dependency `tx_lib` (locked to 0.3.4) of package `tx_handlers v0.3.4 (D:\Programming\projects\tablex\crates\handlers)`
if you are looking for the prerelease package it needs to be specified explicitly
    tauri-specta-macros = { version = "2.0.0-rc.5" }
perhaps a crate was updated and forgotten to be re-vendored?
```
Here are my versions:
```toml
specta = { version = "2.0.0-rc.20", features = ["serde", "serde_json"] }
specta-typescript = "0.0.7"
tauri-specta = { version = "2.0.0-rc.15", features = ["derive", "typescript"] }
```
